### PR TITLE
Added macOS support

### PR DESCRIPTION
**Pull request by brukberhane**
I'm using the Tachidesk-Server icon as the asset as of right now because it looks really nice, but it can be updated to use Sorayomi's assets for a more cohesive look

### CODE REVIEW

**Comment by DattatreyaReddy** [comment]
Thank you for the support!
Can you try to update [publish.yml](https://github.com/Suwayomi/Tachidesk-Sorayomi/blob/main/.github/workflows/publish.yml) file in `.github/workflows` to deploy the macOS version?
You can refer [flutter gallery](https://github.com/flutter/gallery/blob/master/.github/workflows/release_draft_github_release.yml) and [flutter deployment](https://github.com/flutter/gallery/blob/master/.github/workflows/release_draft_github_release.yml)

Or you can join our discord server and ask @mahor1221 to help you with that.

**Comment by DattatreyaReddy** [comment]
Also can you please use the default icon of Tachidesk-Sorayomi?

I just want to make it different from other clients.

P.S. We are open for discussion in changing the icon. (You can join our Discord for more)

**Comment by DattatreyaReddy** [comment]
https://github.com/Suwayomi/Tachidesk-Sorayomi/pull/25#issuecomment-1071017347

**Comment by mahor1221** [comment]
@brukberhane Please test the workflow by publishing a release with a tag like 0.1.3 on your repository. It should look like [Tachidesk-Sorayomi/releases](https://github.com/Suwayomi/Tachidesk-Sorayomi/releases) with MacOS package added to other files. 

If it didn't work there is a possibility that the command on line 112 is the problem. I've removed `--keepParent Flutter\ Gallery.app` as I don't know what it does. Maybe you want to change it.
``` 
      - name: Compress build for macOS
        if: matrix.target == 'macos'
        working-directory: ${{ matrix.build_path }}
112 ==> run: ditto -c -k --sequesterRsrc "$GITHUB_WORKSPACE/${{ env.pkg_name }}-${{ github.ref_name }}-${{ matrix.target }}-x64.zip"
        # run: ditto -c -k --sequesterRsrc --keepParent Flutter\ Gallery.app $GITHUB_WORKSPACE/${{ env.pkg_name }}-${{ github.ref_name }}-${{ matrix.target }}.zip
```

**Comment by DattatreyaReddy** [comment]
@brukberhane is deployment working properly?
Going to release v0.1.3 the day after tomorrow.
Can you conform it by then?

**Comment by brukberhane** [comment]
Hey @mahor1221 and @DattatreyaReddy, sorry I've not replied in a while. I'm currently in the middle of exams and been struggling with balancing that with my work. I'll be finished in a couple of days and I'll be testing the releases until then. Until then, you guys have access to my repo because you're contributors and all that so you could edit it to @mahor1221's specifications and see if it works for you guys. If you can afford to wait though, I'll be on it in a little while.

**Comment by DattatreyaReddy** [comment]
I'm also in similar situation ☺️. My exams starts from Monday 😭. No problem we will wait. We don't have Mac so we can't test it.😶

**Comment by brukberhane** [comment]
@DattatreyaReddy I'm working on it right now. As @mahor1221 mentioned, the ditto command is a bit problematic so I'll let you know as soon as it works

**Comment by brukberhane** [comment]
Alright, so @DattatreyaReddy, builds look to be working. The macos app is ready to deploy from a workflow

**Comment by DattatreyaReddy** [comment]
We shall release new version next week. 👍

**Comment by brukberhane** [comment]
Awesome! Glad I could help with that

**Comment by DattatreyaReddy** [comment]
You are always welcome to support the development

**Comment by DattatreyaReddy** [comment]
Hey @brukberhane, the macOS build is throwing errors in GitHub actions. Can you look into this?

**Comment by brukberhane** [comment]
Sure, it seems like the -enable-linux-support flag in the flutter config is being weird. I'll clone and see if I can recreate the bug

**Comment by brukberhane** [comment]
It seems that we need to enable Rosetta on the workflow runner before we do anything else.... @mahor1221 if you have any tips for this I'd appreciate it

**Comment by brukberhane** [comment]
Ok, so the Github runner doesn't isn't able to enable rosetta and stuff like that. It gives me an error telling me that it's an Intel Mac. Which makes the workflow error for an unsupported architecture really weird. I'm stumped here...

**Comment by matthewdias** [comment]
@brukberhane i think this is the real issue https://github.com/subosito/flutter-action/issues/146

**Comment by brukberhane** [comment]
Thank you for pointing me in the right direction @matthewdias! I'll keep track of that issue and we can upgrade `flutter-action` once it's fixed.

**Comment by matthewdias** [comment]
the fix was released, i think if @DattatreyaReddy reruns the failed workflow it should work? https://github.com/subosito/flutter-action/releases/tag/v2.4.0

**Comment by DattatreyaReddy** [comment]
Let's have a new release after few days. Most probably a week.

**Comment by DattatreyaReddy** [comment]
I'm re-running macos built.

**Pull request merged**
